In [15]:
import numpy as np
list1=[[2,3,4],[3,3,4,],[3,4,5]]
twod=np.array(list1)
print(twod.shape)
print(twod.ndim)
print(twod.size)
print(twod[0,0])
print(twod)
print(twod[1])
print(twod[2,1:])
print(twod+(np.array([[2,3,4],[3,3,4,],[3,4,5]])))
print(np.sin(twod))
print(twod.T)

(3, 3)
2
9
2
[[2 3 4]
 [3 3 4]
 [3 4 5]]
[3 3 4]
[4 5]
[[ 4  6  8]
 [ 6  6  8]
 [ 6  8 10]]
[[ 0.90929743  0.14112001 -0.7568025 ]
 [ 0.14112001  0.14112001 -0.7568025 ]
 [ 0.14112001 -0.7568025  -0.95892427]]
[[2 3 3]
 [3 3 4]
 [4 4 5]]
